name: Wayback On GitHub

on:
  push:
      branches:
        - "**"
  pull_request:
      branches: [ main ]
      types: [ opened, synchronize, reopened ]

  schedule:
    - cron: '0 */6 * * *'

jobs:
  wayback:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    continue-on-error: true
    steps:
    - name: Run wayback service
      uses: wabarc/on-github@v0.0.1
      env:
        WAYBACK_TELEGRAM_TOKEN: ${{ secrets.WAYBACK_TELEGRAM_TOKEN }}
        WAYBACK_DAEMON:'telegram'
        WAYBACK_TO: 'ip,ph'
